# Generated by Django 3.1.3 on 2022-05-30 12:59

import address.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_registration_app', '0001_initial'),
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жилого помещения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание жилого помещения')),
                ('type', models.CharField(choices=[('HOTEL', 'Отель'), ('APARTMENT', 'Квартира'), ('HOUSE', 'Дом'), ('HOSTEL', 'Хостел'), ('COTTAGE', 'Коттедж')], max_length=15, verbose_name='Тип жилого помещения')),
                ('rooms_qty', models.PositiveIntegerField(verbose_name='Количество комнат/номеров')),
                ('people_capacity', models.PositiveIntegerField(verbose_name='Вместимость жилого помещения (человек)')),
                ('price', models.PositiveIntegerField(verbose_name='Цена за день проживания')),
                ('add_date', models.DateField(default=datetime.datetime(2022, 5, 30, 12, 59, 52, 258911, tzinfo=utc), verbose_name='Дата добавления')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Оценка жилого помещения')),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='login_registration_app.owner')),
            ],
            options={
                'verbose_name': 'properties',
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Уникальный идентификатор удобсва')),
                ('img', models.ImageField(upload_to='facility_icons/', verbose_name='Иконка')),
                ('name', models.CharField(max_length=15, verbose_name='Название удобсва')),
                ('is_search_service', models.BooleanField(blank=True, default=False, verbose_name='Удобство используется при поиске?')),
                ('properties', models.ManyToManyField(blank=True, null=True, related_name='services', to='reservation_app.Property', verbose_name='Помещение с удобством')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('kids_qty', models.PositiveIntegerField(verbose_name='Количество детей')),
                ('adults_qty', models.PositiveIntegerField(verbose_name='Количество взрослых')),
                ('booked_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation_app.property', verbose_name='Забронированное помещение')),
                ('resident_who_booked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='login_registration_app.resident', verbose_name='Человек, который забронировал помещение')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reservation_app.property')),
            ],
        ),
    ]
