# Generated by Django 3.1.3 on 2022-05-16 22:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'properties', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 16, 22, 45, 16, 32494, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
