# Generated by Django 3.1.3 on 2022-05-17 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_auto_20220517_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 17, 6, 51, 35, 557202, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка жилого помещения'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms_qty',
            field=models.PositiveIntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='service',
            name='properties',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='reservation_app.Property', verbose_name='Помещение с удобством'),
        ),
    ]
