# Generated by Django 3.1.3 on 2022-05-22 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_auto_20220517_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='people_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Вместимость жилого помещения (человек)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 15, 47, 1, 406211, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms_qty',
            field=models.PositiveIntegerField(verbose_name='Количество комнат/номеров'),
        ),
    ]
