# Generated by Django 3.1.3 on 2022-05-24 22:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0004_auto_20220522_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 22, 18, 35, 533000, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
