# Generated by Django 3.1.3 on 2022-05-26 19:56

import address.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('reservation_app', '0005_auto_20220525_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 26, 19, 56, 22, 129800, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=address.models.AddressField(default=None, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
