# Generated by Django 3.1.3 on 2022-05-28 23:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0007_auto_20220528_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 28, 23, 18, 11, 466000, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(verbose_name='Цена за день проживания'),
        ),
    ]
