# Generated by Django 3.1.3 on 2022-05-28 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0008_auto_20220529_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='add_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 28, 23, 20, 14, 336000, tzinfo=utc), verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена за день проживания'),
        ),
    ]
