# Generated by Django 3.1.3 on 2022-05-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'owners', 'verbose_name_plural': 'owners'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'residents', 'verbose_name_plural': 'residents'},
        ),
        migrations.AddField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='owners_images/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='residents_images/'),
        ),
    ]
